// "Did you know?" cards. One is picked at random on each page load.
// Categories: History, People, Fun, Real world, Internals, Tip
LAB.FACTS = [
  ['History', 'In June 1970, Edgar F. Codd of IBM published "A Relational Model of Data for Large Shared Data Banks". Every table you query in this lab comes from that paper.'],
  ['History', 'SQL was first called SEQUEL (Structured English Query Language). IBM renamed it SQL because another company already owned the trademark "SEQUEL".'],
  ['History', 'SQL was designed at IBM in 1974 by Donald Chamberlin and Raymond Boyce, the same Boyce from Boyce–Codd Normal Form (BCNF).'],
  ['History', 'The first commercial SQL database was Oracle V2, released in 1979. There was never an Oracle V1: the company thought "version 2" sounded more trustworthy.'],
  ['History', 'IBM\'s System R (1974–1979) was the first system to run SQL. Many ideas you use today, like the cost-based query optimizer, come from that project.'],
  ['History', 'SQL became an ANSI standard in 1986 and an ISO standard in 1987. The latest version is SQL:2023.'],
  ['History', 'IBM\'s IMS database was built in the 1960s for NASA\'s Apollo program, to track the millions of parts of the Saturn V rocket. Banks still use it today.'],
  ['History', 'Peter Chen introduced the Entity–Relationship model in 1976. The ER diagrams you draw on Day 9 are almost 50 years old.'],
  ['History', 'Codd defined 1NF, 2NF and 3NF in 1971. BCNF followed in 1974.'],
  ['History', 'In 1985, Codd published 12 rules a database must follow to be called "relational". There are actually 13: the list starts at Rule 0.'],
  ['History', 'The word "NoSQL" was first used in 1998 by Carlo Strozzi for a relational database that did not use SQL. It became popular again in 2009 as the name of a meetup.'],
  ['History', 'Window functions (ROW_NUMBER, RANK, running totals) became part of the SQL standard in 2003. MySQL only added them in version 8.0, in 2018.'],
  ['History', 'SQLite added window functions in 2018 and RIGHT and FULL OUTER JOIN only in 2022.'],
  ['History', 'The Halloween Problem was found at IBM on Halloween 1976. A query giving a 10% raise to everyone earning under $25,000 kept raising the same people until nobody was under $25,000. The update was reading an index it was changing at the same time.'],
  ['People', 'Four Turing Awards (the "Nobel Prize of computing") went to database pioneers: Charles Bachman (1973), Edgar Codd (1981), Jim Gray (1998) and Michael Stonebraker (2014).'],
  ['People', 'Jim Gray won his Turing Award for his work on transactions. The ACID properties you learn on Day 11 build on his ideas.'],
  ['People', 'The acronym ACID was coined in 1983 by Theo Härder and Andreas Reuter.'],
  ['People', 'MySQL is named after My, the daughter of its co-founder Michael "Monty" Widenius. His later database, MariaDB, is named after his younger daughter, Maria.'],
  ['People', 'PostgreSQL started in 1986 at UC Berkeley as "Postgres", meaning "after Ingres", an older database from the same lab.'],
  ['People', 'SQLite was written by D. Richard Hipp in 2000 for software on a US Navy destroyer. He needed a database that worked without a server or an administrator.'],
  ['People', 'Larry Ellison started Oracle after reading IBM\'s published research on relational databases. He shipped a product before IBM did.'],
  ['Fun', 'The official way to say SQL is "S-Q-L", letter by letter. Millions of developers still say "sequel". Both are fine in interviews.'],
  ['Fun', 'SQLite has no license. Its source code is in the public domain and starts with a blessing: "May you do good and not evil. May you find forgiveness for yourself and forgive others."'],
  ['Fun', 'The PostgreSQL elephant is called Slonik, which means "little elephant" in Russian.'],
  ['Fun', 'The MySQL dolphin is called Sakila. The name came from a user contest and was suggested by a developer from Eswatini.'],
  ['Fun', 'MongoDB got its name from the word "humongous".'],
  ['Fun', 'Redis stands for REmote DIctionary Server.'],
  ['Fun', 'xkcd comic #327 shows a mother who named her son Robert\'); DROP TABLE Students;-- . The school database deleted its students table. Fans call him "Little Bobby Tables".'],
  ['Fun', 'A SQL query walks into a bar, goes up to two tables and asks: "Can I join you?"'],
  ['Fun', 'SELECT * FROM people WHERE has_read_the_error_message = 1; → 0 rows. Read the error message. It usually tells you the exact problem.'],
  ['Fun', 'Nobody is sure what the "B" in B-tree stands for. It could be Boeing (where it was invented), balanced, broad, or Bayer (one of its inventors). The inventors never said.'],
  ['Fun', 'SQL keywords are not case-sensitive. SELECT, select and SeLeCt all work. Uppercase keywords are only a convention that makes queries easier to read.'],
  ['Real world', 'SQLite is the most widely used database engine in the world. It runs on every Android phone and iPhone, in every major web browser, and in many cars and planes. Its authors estimate over one trillion SQLite databases are in use.'],
  ['Real world', 'Wikipedia runs on MariaDB, the open-source fork of MySQL.'],
  ['Real world', 'In 2017, an engineer at GitLab accidentally deleted a production database. Five different backup methods all turned out to be broken. The company live-streamed the recovery and lost about six hours of data. Lesson: test your backups.'],
  ['Real world', 'Google Spanner keeps data consistent across the planet using atomic clocks and GPS receivers in its data centers.'],
  ['Real world', 'Apache Cassandra was built at Facebook in 2008 to power inbox search.'],
  ['Real world', 'SQL injection was first publicly described in 1998. It is still on the OWASP Top 10 list of the most critical web security risks.'],
  ['Real world', 'SQLite is tested to the same standard as flight software for aircraft: 100% branch test coverage. Its test code is hundreds of times larger than the database code itself.'],
  ['Real world', 'One SQLite database file can be up to about 281 terabytes.'],
  ['Internals', 'A B+ tree with 100 keys per node needs only 4 levels to index 100 million rows. That is why an indexed lookup is fast even on huge tables.'],
  ['Internals', 'In SQLite, every PRIMARY KEY and UNIQUE constraint creates an index automatically. Run EXPLAIN QUERY PLAN to see it used.'],
  ['Internals', 'Databases write changes to a log before they change the data file. This is write-ahead logging (WAL), and it is how a database survives a power cut in the middle of a transaction.'],
  ['Internals', 'The ARIES recovery algorithm, published by IBM\'s C. Mohan in 1992, is still the basis of crash recovery in most big databases.'],
  ['Internals', 'In relational theory a table is a set, so duplicate rows cannot exist. SQL tables are "bags" (multisets) and allow duplicates. That is why DISTINCT exists.'],
  ['Internals', 'In Oracle, an empty string \'\' is treated as NULL. In PostgreSQL, MySQL and SQLite, \'\' and NULL are different values.'],
  ['Internals', 'SQLite lets you store text in an INTEGER column. Since 2021 you can add STRICT to CREATE TABLE to make types strict, like in other databases.'],
  ['Internals', 'With recursive CTEs (Day 6), SQL is Turing complete: in theory it can compute anything a normal programming language can.'],
  ['Internals', 'The CAP theorem (Eric Brewer, 2000) says a distributed database cannot guarantee consistency, availability and partition tolerance all at once. It was proved in 2002.'],
  ['Internals', 'Codd later proposed two kinds of NULL: "missing but applicable" (we do not know the phone number) and "not applicable" (this person has no phone). SQL kept only one.'],
  ['Internals', 'The query optimizer may run your joins in a completely different order than you wrote them. SQL describes what you want, not how to get it.'],
  ['Tip', '"The key, the whole key, and nothing but the key, so help me Codd." This classic line sums up 1NF, 2NF and 3NF.'],
  ['Tip', 'Before you run an UPDATE or a DELETE, run it as a SELECT with the same WHERE. If the SELECT returns the wrong rows, so would your UPDATE.'],
  ['Tip', 'NULL = NULL is not TRUE. It is UNKNOWN. To find missing values, always write IS NULL.'],
  ['Tip', 'COUNT(*) counts rows. COUNT(column) counts only the rows where that column is not NULL. They can give different answers on the same table.'],
  ['Tip', 'A WHERE condition on the right table of a LEFT JOIN quietly turns it into an INNER JOIN. Put that condition in the ON clause instead.'],
  ['Tip', 'Without ORDER BY, the database may return rows in any order, and the order can change between runs.'],
  ['Tip', 'NOT IN with a list that contains a NULL returns no rows at all. Use NOT EXISTS when NULLs are possible.'],
  ['Tip', 'Wrapping an indexed column in a function, like WHERE UPPER(name) = \'ALI\', usually stops the database from using the index.'],
  ['Tip', 'Never build SQL by gluing user input into a string. Use parameterized queries (placeholders like ?), and SQL injection becomes impossible.'],
  ['Tip', 'Read a query in the order the database runs it: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY → LIMIT. The Query X-ray in this lab shows exactly that.']
];
